// react/src/components/Head.tsx
//import { Routes, Route, Link } from 'react-router-dom';
import React from "react";
import {Link } from 'react-router-dom';
//
function Page() {
    return (
    <div>
        <Link to="/">Home</Link>
        <Link to="/about">&nbsp; [ about ]</Link>
        <hr />
    </div>
    );
}
export default Page;
/*
*/

// svelte-app/src/components/Head.svelte
<script>
	import {link} from 'svelte-spa-router'
</script>

<header class="">
  <div class="container">
    <span><a href="/" use:link>[ Home ]</a>
    </span>
    <span><a href="/about" use:link>[ about ]</a>
    </span>
    <span><a href="/task_project" use:link>[ TaskProject ]</a>
    </span>
  </div>
  <hr />
</header>

<!--
-->
