// react-app/src/client/TaskItems/Create.tsx
import React from "react";
import {useState, useEffect}  from 'react';
import { Link } from 'react-router-dom';
import { useSearchParams } from 'react-router-dom';
import { useNavigate } from "react-router-dom";
import { z } from 'zod';
import moment from "moment";
import ApiUtil from '../../lib/ApiUtil';
import ApiUtil from '../../lib/ApiUtil';
import Crud from './Crud';
import CrudCreate from './CrudCreate';
import { todoSchema } from './types';

let data: any ={items: []}
let project = {};
let items = [];
let itemsNone = [], itemsWorking = [], itemsComplete = [];
//let complete = "", start_date= "";

export default function Page (){
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [updateTime, setUpdateTime] = useState("");
  const [id, setId] = useState(0);
  const [selectedValue, setSelectedValue] = useState('1');
  const [startDate, setStartDate] = useState('');
  const [complete, setComplete] = useState('');
  const [errors, setErrors] = useState({});

  useEffect(() => {
    const fetchTodos = async () => {
      try {
        const tmpId = searchParams.get('id'); // ?xx=の値を取得
        setId(tmpId);
        console.log("tmpId=", tmpId);
        const dt = moment().format('YYYY-MM-DD');
        setStartDate(dt);
        setComplete(dt);  
        setUpdateTime(new Date().getTime());
      } catch (error) {
        console.error('Error fetching todos:', error);
      }
    };
    fetchTodos();
  }, []);

  // ラジオボタンの変更を処理する関数
  const handleRadioChange = (event) => {
    setSelectedValue(event.target.value);
  };

  const saveProc = async function() {
    try{
      setErrors({});
      let values = Crud.getInputValues();
  console.log(values); 
      const validatedTodo = todoSchema.parse(values);
  console.log("#save.selected=", selectedValue); 
      const resulte = await CrudCreate.addItem(Number(id), selectedValue);
  console.log(resulte);
      if(resulte.ret === 200) {
        navigate(`/task_project_show?id=${id}`);
      }
    } catch (error) {
      console.error(error);
      if (error instanceof z.ZodError) {
        const target = error.errors.reduce((acc, curr) => {
          const field = curr.path[0];
          acc[field] = curr.message;
          return acc;
        }, {});
        setErrors(target);
        console.log(target);
      }
    }    
  }

  return (
  <div className="min-h-screen flex items-center justify-center bg-gray-100">
    <div className="bg-white p-8 rounded shadow-md w-full max-w-sm">
      <Link className="btn-outline-blue" to={`/task_project_show?id=${id}`}
      >Back</Link>
      <hr className="my-2" />
      <h1 className="text-3xl -font-bold">TaskCreate</h1>
      projectId: {id}
      <hr className="my-2" />
      <div className="col-md-9 form-group">
        <label className="fw-bold ">Title:</label>
        <input type="text" name="title" id="title" 
        className="input_text" />
        {errors.title ? (
          <p className="text-red-500 text-sm mt-1">{errors.title}</p>
        ) : null}
      </div>
      {/* status */}
      <div>
        <label>
          <input
            type="radio"
            value="1"
            checked={selectedValue === '1'}
            onChange={handleRadioChange}
            className="ms-2"
          />
          none
        </label>
        <label>
          <input
            type="radio"
            value="2"
            checked={selectedValue === '2'}
            onChange={handleRadioChange}
            className="ms-2"
          />
          working
        </label>
        <label>
          <input
            type="radio"
            value="3"
            checked={selectedValue === '3'}
            onChange={handleRadioChange}
            className="ms-2"
          />
          complete
        </label>

      </div>
      <hr className="mt-2 mb-2" />
      <div className="col-md-6 form-group">
        <label clasclassNames="col-sm-12">Start:</label>
        <input type="date"  className="input_text"  id="start_date" name="start_date"                   
        value={startDate} required="required"
        onChange={(e) => setStartDate(e.target.value)} />        
      </div>
      <div className="col-md-6 form-group">
        <label className="col-sm-12">End:</label>
        <input type="date"  className="input_text"  id="complete" name="complete"                   
        value={complete} required="required"
        onChange={(e) => setComplete(e.target.value)} />        
      </div>
      <div className="col-md-6 form-group">
        <label for="content">Content:</label>
        <textarea id="content" name="content" required 
        className="input_textarea"
        rows="10" placeholder=""></textarea>
      </div>       
      <button  
      onClick={() => saveProc()}
      className="btn btn-primary my-2">Save</button>

    </div>

  </div>
  );
}

// svelte-app/src/client/task_items/Create.svelte
<svelte:head>
<title>Show</title>
<meta name="description" content="About this app" />
</svelte:head>

<script lang="ts">
import {location, querystring} from 'svelte-spa-router';
import {link, push} from 'svelte-spa-router';
let selected = 1;
import { z } from "zod";
import { onMount } from 'svelte';
//import LibConfig from '$lib/LibConfig';
import LibCommon from '../../lib/LibCommon';
import CrudCreate from "./CrudCreate";
import Crud from './Crud';
import { todoSchema } from './create/types';

/** @type {import('./$types').PageData} */
export let data: any, item: any= {}, post_id = 0, content = "", id = 0;
let messageModal = "";
let complete = "", start_date= "";
let errors: { [key: string]: string } = {};
//
const startProc= async function() {
  const dt = LibCommon.formatDate(new Date(), 'YYYY-MM-DD');
  complete = dt;
  start_date = dt;
//console.log(complete);
}
onMount(async () => {
  try {
    const idValue = $querystring.replace("id=", '');
    console.log("idValue=", idValue);
    id = Number(idValue);
    startProc();

  } catch (e) {
    console.log(e);
  }
});

/**
*
* @param
*
* @return
*/
const save = async function() {
  try{
    errors = {};
    let values = Crud.getInputValues();
console.log(values); 
    const validatedTodo = todoSchema.parse(values);
console.log("#save.selected=", selected); 
    const resulte = await CrudCreate.addItem(Number(id), selected);
console.log(resulte);
    if(resulte.ret === 200) {
      //location.href = `/task_project_show?id=${id}`;
      push(`/task_project_show?id=${id}`);
    }
  } catch (error) {
    console.error(error);
    if (error instanceof z.ZodError) {
			errors = error.errors.reduce((acc, curr) => {
				const field = curr.path[0];
				acc[field] = curr.message;
				return acc;
			}, {});
		}
    console.log(errors);
  }    
}
</script>

<!-- CSS -->
<style>
</style>

<!-- MarkUp -->
<div class="min-h-screen flex items-center justify-center bg-gray-100">
	<div class="bg-white p-8 rounded shadow-md w-full max-w-sm">
    <a class="btn-outline-blue" href={`/task_project_show?id=${id}`}
    use:link
    >Back</a>
    <hr class="my-2" />
    <h1 class="text-3xl -font-bold">TaskCreate</h1>
    projectId: {id}
    <hr class="my-2" />
    <div class="col-md-9 form-group">
      <label class="fw-bold ">Title:</label>
      <input type="text" name="title" id="title" 
      class="input_text" />
      {#if errors.title}
			<p class="text-red-500 text-sm mt-1">{errors.title}</p>
			{/if}
    </div>
    <hr class="my-2" />
    <label>
        <input bind:group={selected} type="radio" name="amount" value={1} 
        class="form-check-input mx-2" />none
    </label>
    <label>
        <input bind:group={selected} type="radio" name="amount" value={2} 
        class="form-check-input mx-2" />working
    </label>
    <label>
        <input bind:group={selected} type="radio" name="amount" value={3} 
        class="form-check-input mx-2" />complete
    </label>
    <hr class="mt-2 mb-2" />
    <div class="col-md-6 form-group">
        <label class="col-sm-12">Start:</label>
        <input type="date"  class="input_text"  id="start_date" name="start_date"                   
        value={start_date} required="required" />        
    </div>
    <hr class="mt-2 mb-2" />
    <div class="col-md-6 form-group">
        <label class="col-sm-12">End:</label>
        <input type="date"  class="input_text"  id="complete" name="complete"                   
        value={complete} required="required" />        
    </div>
    <hr />
    <div class="col-md-6 form-group">
        <label for="content">Content:</label>
        <textarea id="content" name="content" required 
        class="input_textarea"
        rows="10" placeholder=""></textarea>
    </div> 
    <button on:click={save} class="btn btn-primary my-2">Save</button>
  </div>
</div>

<!--
-->
